/** Parametric interchange for the OVERHAUL reconstructed asset model. */
import type { TwinModel } from "./twinModel";

export type InteropScope = "building" | "facility" | "equipment";
export interface InteropAsset { id:string; name:string; scope:InteropScope; className:string; widthM:number; depthM:number; heightM:number; capacityKW?:number|null; powerKW?:number|null; evidenceIds?:string[]; }
export interface InteropManifest { schema:"overhaul.asset.v1"; asset:InteropAsset; coordinateSystem:"right-handed-z-up"; geometryBasis:"parametric-dimensions"|"reconstructed-twin"|"unresolved"; engineeringValues:Array<{key:string;value:number|string;unit?:string}>; provenance:Array<{type:"evidence"|"derived";id:string;note:string}>; targets:Array<"Blender"|"AutoCAD/DXF"|"BIM/IFC-ready manifest">; twinModel?:TwinModel; }

function requireDimension(value:number,label:string){if(!Number.isFinite(value)||value<=0)throw new Error(`Cannot export geometry: ${label} is unresolved.`);return value;}
function boxObj(name:string,width:number,depth:number,height:number,ox=0,oy=0,oz=0){const x0=ox,x1=ox+width,y0=oy,y1=oy+depth,z0=oz,z1=oz+height;return [`o ${name}`,`v ${x0} ${y0} ${z0}`,`v ${x1} ${y0} ${z0}`,`v ${x1} ${y1} ${z0}`,`v ${x0} ${y1} ${z0}`,`v ${x0} ${y0} ${z1}`,`v ${x1} ${y0} ${z1}`,`v ${x1} ${y1} ${z1}`,`v ${x0} ${y1} ${z1}`,"f -8 -7 -6 -5","f -4 -3 -2 -1","f -8 -4 -3 -7","f -2 -6 -5 -1","f -8 -5 -1 -4","f -7 -3 -2 -6"].join("\n");}
export function buildTwinObj(model:TwinModel){const parts:string[]=["# OVERHAUL reconstructed twin export","# Units: metres","# Coordinate system: right-handed / Z-up"];for(const room of model.rooms)parts.push(boxObj(`ROOM_${room.id}`,room.widthM,room.depthM,.08,room.x,room.y,0));for(const wall of model.walls){const dx=wall.b.x-wall.a.x,dy=wall.b.y-wall.a.y,len=Math.hypot(dx,dy),cx=(wall.a.x+wall.b.x)/2,cy=(wall.a.y+wall.b.y)/2;const base=boxObj(`WALL_${wall.id}`,len,wall.thicknessM,wall.heightM,-len/2,-wall.thicknessM/2,0);parts.push(base,`# WALL ${wall.id} center ${cx} ${cy} rotation_deg ${Math.atan2(dy,dx)*180/Math.PI}`);}for(const asset of model.assets)parts.push(boxObj(`ASSET_${asset.id}`,asset.widthM,asset.depthM,asset.heightM,asset.x-asset.widthM/2,asset.y-asset.depthM/2,0));return `${parts.join("\n")}\n`;}
export function buildAssetObj(asset:InteropAsset){const w=requireDimension(asset.widthM,"width"),d=requireDimension(asset.depthM,"depth"),h=requireDimension(asset.heightM,"height");const secondary=asset.scope!=="equipment"?boxObj("HVAC_ZONE",Math.max(w*.18,1),Math.max(d*.18,1),Math.max(h*.35,1),w*.41,d*.41,h):boxObj("SERVICE_CLEARANCE",w*.82,d*.82,Math.max(h*.06,.05),w*.09,d*.09,h);return ["# OVERHAUL parametric asset export",`# Asset: ${asset.name}`,"# Units: metres",boxObj(asset.className.replace(/\s+/g,"_"),w,d,h),secondary,""] .join("\n");}
export function buildDxfFootprint(asset:InteropAsset){const w=requireDimension(asset.widthM,"width"),d=requireDimension(asset.depthM,"depth"),points=[[0,0],[w,0],[w,d],[0,d],[0,0]],entities=points.slice(0,-1).map((p,i)=>{const q=points[i+1];return `0\nLINE\n8\nOVERHAUL\n10\n${p[0]}\n20\n${p[1]}\n30\n0\n11\n${q[0]}\n21\n${q[1]}\n31\n0`;}).join("\n");return ["0","SECTION","2","HEADER","0","ENDSEC","0","SECTION","2","ENTITIES",entities,"0","ENDSEC","0","EOF",""] .join("\n");}
export function buildTwinDxf(model:TwinModel){const lines:string[]=[];for(const wall of model.walls)lines.push(`0\nLINE\n8\nWALLS\n10\n${wall.a.x}\n20\n${wall.a.y}\n30\n0\n11\n${wall.b.x}\n21\n${wall.b.y}\n31\n0`);for(const room of model.rooms){const p=[[room.x,room.y],[room.x+room.widthM,room.y],[room.x+room.widthM,room.y+room.depthM],[room.x,room.y+room.depthM],[room.x,room.y]];for(let i=0;i<4;i+=1){const a=p[i],b=p[i+1];lines.push(`0\nLINE\n8\nROOMS\n10\n${a[0]}\n20\n${a[1]}\n30\n0\n11\n${b[0]}\n21\n${b[1]}\n31\n0`);}}for(const asset of model.assets)lines.push(`0\nPOINT\n8\nASSETS\n10\n${asset.x}\n20\n${asset.y}\n30\n0`);return ["0","SECTION","2","HEADER","9","$INSUNITS","70","6","0","ENDSEC","0","SECTION","2","ENTITIES",...lines,"0","ENDSEC","0","EOF",""] .join("\n");}
export function buildInteropManifest(asset:InteropAsset,values:Record<string,number|string|null|undefined>,twin?:TwinModel|null):InteropManifest{const resolved=Boolean(twin)||[asset.widthM,asset.depthM,asset.heightM].every(x=>Number.isFinite(x)&&x>0);const engineeringValues=Object.entries(values).filter(([,v])=>v!=null&&v!=="").map(([key,value])=>({key,value:value as number|string})).slice(0,64);return{schema:"overhaul.asset.v1",asset,coordinateSystem:"right-handed-z-up",geometryBasis:twin?"reconstructed-twin":resolved?"parametric-dimensions":"unresolved",engineeringValues,provenance:[...(asset.evidenceIds??[]).map(id=>({type:"evidence" as const,id,note:"Source evidence linked to the asset model."})),{type:"derived" as const,id:"reconstruction",note:twin?"Browser/CAD geometry generated from the reconstructed OVERHAUL twin model.":"Parametric geometry generated from explicitly supplied dimensions."}],targets:["Blender","AutoCAD/DXF","BIM/IFC-ready manifest"],...(twin?{twinModel:twin}:{})};}
