"use client";

import { useMemo, useState } from "react";
import { buildAssetObj, buildDxfFootprint, buildInteropManifest, buildTwinDxf, buildTwinObj, type InteropAsset } from "@/lib/engineering/assetInteroperability";
import type { TwinModel } from "@/lib/engineering/twinModel";

type Props={scope:"building"|"facility"|"equipment";title:string;assetClass:string;evidenceIds:string[];values:Record<string,number|string|null|undefined>;twin?:TwinModel|null};
function downloadText(filename:string,content:string,type:string){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
function n(values:Props["values"],...keys:string[]){for(const key of keys){const value=Number(values[key]);if(Number.isFinite(value)&&value>0)return value;}return null;}

export default function AssetTwinViewport({scope,title,assetClass,evidenceIds,values,twin}:Props){
  const [tab,setTab]=useState<"model"|"evidence">("model");
  const width=twin?.overall.widthM??n(values,"geometry_width_m","width_m"); const depth=twin?.overall.depthM??n(values,"geometry_depth_m","depth_m"); const height=twin?.overall.heightM??n(values,"geometry_height_m","height_m");
  const asset:InteropAsset=useMemo(()=>({id:"asset-core",name:title,scope,className:assetClass,widthM:width??1,depthM:depth??1,heightM:height??1,capacityKW:n(values,"capacity_kw"),powerKW:n(values,"power_kw"),evidenceIds}),[assetClass,depth,evidenceIds,height,scope,title,values,width]);
  const manifest=useMemo(()=>buildInteropManifest(asset,values,twin),[asset,twin,values]); const safeName=title.replace(/\W+/g,"-").replace(/^-|-$/g,"")||"overhaul-twin";
  const generated=Boolean(twin); const hasDims=Boolean(width&&depth&&height);
  const floorPlan=twin?{rooms:twin.rooms,walls:twin.walls,assets:twin.assets}:{rooms:[],walls:[],assets:[]};
  return <section className="overflow-hidden border border-teal/20 bg-[#070b0b] shadow-[0_24px_100px_rgba(0,0,0,.22)]"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-steel/10 px-5 py-4"><div><p className="font-mono text-[8px] uppercase tracking-[.16em] text-teal">Reconstructed twin · CAD bridge</p><h2 className="mt-1 font-display text-3xl">The model is an artifact, not a mock.</h2><p className="mt-1 max-w-3xl text-[10px] leading-5 text-steel">A generated floor-plan model is stored as semantic rooms, walls, openings and assets, then exported into editable geometry rather than a screenshot.</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={!generated&&!hasDims} onClick={()=>downloadText(`${safeName}.obj`,generated?buildTwinObj(twin!):buildAssetObj(asset),"text/plain;charset=utf-8")} className="border border-teal/30 px-3 py-2 font-mono text-[8px] uppercase text-teal disabled:opacity-30">Export OBJ</button><button type="button" disabled={!generated&&!hasDims} onClick={()=>downloadText(`${safeName}.dxf`,generated?buildTwinDxf(twin!):buildDxfFootprint(asset),"application/dxf")} className="border border-steel/25 px-3 py-2 font-mono text-[8px] uppercase text-paper disabled:opacity-30">Export DXF</button><button type="button" onClick={()=>downloadText(`${safeName}.overhaul.json`,JSON.stringify(manifest,null,2),"application/json")} className="border border-steel/25 px-3 py-2 font-mono text-[8px] uppercase text-paper">Twin manifest</button></div></div>
    <div className="grid gap-0 xl:grid-cols-[1fr_.75fr]"><div className="relative min-h-[430px] border-b border-steel/10 bg-[#040707] xl:border-b-0 xl:border-r"><div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] bg-[size:32px_32px]"/>
      <svg viewBox={`0 0 ${Math.max(twin?.overall.widthM??10,10)} ${Math.max(twin?.overall.depthM??8,8)}`} className="relative h-[430px] w-full p-8" role="img" aria-label="Generated floor plan and asset layout">{twin?.rooms.map((room)=><rect key={room.id} x={room.x} y={room.y} width={room.widthM} height={room.depthM} fill="rgba(44,224,202,.045)" stroke="rgba(44,224,202,.28)" strokeWidth=".04"/>)}{twin?.walls.map((wall)=><line key={wall.id} x1={wall.a.x} y1={wall.a.y} x2={wall.b.x} y2={wall.b.y} stroke="rgba(220,240,236,.7)" strokeWidth={Math.max(wall.thicknessM,.08)} vectorEffect="non-scaling-stroke"/>)}{twin?.openings.map((opening)=><circle key={opening.id} cx={opening.x} cy={opening.y} r={Math.max(opening.widthM*.18,.08)} fill={opening.type==="window"?"rgba(44,224,202,.8)":"rgba(228,184,96,.8)"}/>)}{twin?.assets.map((item)=><g key={item.id}><rect x={item.x-item.widthM/2} y={item.y-item.depthM/2} width={item.widthM} height={item.depthM} fill="rgba(228,184,96,.16)" stroke="rgba(228,184,96,.8)" strokeWidth=".05" transform={`rotate(${item.rotationDeg} ${item.x} ${item.y})`}/><text x={item.x} y={item.y} textAnchor="middle" dominantBaseline="middle" fill="rgba(239,248,246,.8)" fontSize=".32">{item.label.slice(0,16)}</text></g>)}</svg><div className="absolute bottom-4 left-4 right-4 flex justify-between gap-3 font-mono text-[7px] uppercase tracking-[.12em] text-steel"><span>{generated?twin?.geometryBasis:"parametric geometry"}</span><span>{generated?`${floorPlan.rooms.length} rooms · ${floorPlan.walls.length} walls · ${floorPlan.assets.length} assets`:"no reconstructed topology"}</span></div></div>
      <aside className="p-5"><div className="flex border border-steel/15 bg-black/20 p-1"><button type="button" onClick={()=>setTab("model")} className={`flex-1 px-3 py-2 font-mono text-[8px] uppercase ${tab==="model"?"bg-teal text-navy":"text-steel"}`}>Model</button><button type="button" onClick={()=>setTab("evidence")} className={`flex-1 px-3 py-2 font-mono text-[8px] uppercase ${tab==="evidence"?"bg-teal text-navy":"text-steel"}`}>Evidence links</button></div>
        {tab==="model"?<div className="mt-4 space-y-3"><Data label="Overall" value={`${(width??0).toFixed(2)} × ${(depth??0).toFixed(2)} × ${(height??0).toFixed(2)} m`}/><Data label="Geometry basis" value={generated?twin!.geometryBasis:hasDims?"parametric dimensions":"unresolved"}/><Data label="Twin confidence" value={generated?`${Math.round(twin!.confidence*100)}%`:"—"}/><Data label="Rooms / walls" value={`${floorPlan.rooms.length} / ${floorPlan.walls.length}`}/><Data label="Visible assets" value={String(floorPlan.assets.length)}/>{twin?.warnings?.length?<div className="border border-amber-200/20 bg-amber-200/[.025] p-3 text-[9px] leading-4 text-amber-100">{twin.warnings.slice(0,4).map((w,i)=><p key={i}>› {w}</p>)}</div>:null}</div>:<div className="mt-4 space-y-2">{evidenceIds.map((id)=><div key={id} className="border border-steel/10 p-3"><p className="font-mono text-[7px] uppercase text-teal">linked evidence</p><p className="mt-1 break-all text-[9px] text-paper">{id}</p></div>)}<p className="mt-4 text-[9px] leading-5 text-steel">Each reconstructed object keeps a source type and confidence so the CAD artifact can be traced back to evidence rather than becoming an opaque mesh.</p></div>}
      </aside></div></section>;
}
function Data({label,value}:{label:string;value:string}){return <div className="border border-steel/10 p-3"><p className="font-mono text-[7px] uppercase text-steel">{label}</p><p className="mt-1 text-sm text-paper">{value}</p></div>;}
