"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { buildInteropManifest, buildTwinDxf, buildTwinObj, type InteropAsset } from "@/lib/engineering/assetInteroperability";
import type { TwinAsset, TwinModel } from "@/lib/engineering/twinModel";
import * as THREE from "three";

type Props = { scope: "building" | "facility" | "equipment"; title: string; assetClass: string; evidenceIds: string[]; values: Record<string, number | string | null | undefined>; twin?: TwinModel | null };
type ViewMode = "current" | "retrofit";

function n(values: Props["values"], ...keys: string[]) {
  for (const key of keys) { const value = Number(values[key]); if (Number.isFinite(value) && value > 0) return value; }
  return null;
}
function downloadText(filename: string, content: string, type: string) {
  const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url);
}
function semanticKind(assetClass: string) {
  const s = assetClass.toLowerCase();
  if (/pump/.test(s)) return "pump"; if (/compressor|chiller|refrigeration/.test(s)) return "compressor"; if (/fan|blower|ahu|air handling/.test(s)) return "fan";
  if (/motor|drive|vfd/.test(s)) return "motor"; if (/boiler|tank|vessel|cooling tower/.test(s)) return "vessel"; if (/panel|switchgear|electrical/.test(s)) return "panel";
  if (/duct|diffuser|pipe|piping/.test(s)) return "duct"; if (/window|glazing/.test(s)) return "window"; if (/door/.test(s)) return "door"; return "generic";
}
function makeMaterial(retrofit: boolean) { return new THREE.MeshStandardMaterial({ color: retrofit ? 0xd8a84e : 0x42e2cd, roughness: 0.38, metalness: 0.42, transparent: true, opacity: 0.9 }); }
function makeSecondary(retrofit: boolean) { return new THREE.MeshStandardMaterial({ color: retrofit ? 0xffd98a : 0xc8faf4, roughness: 0.25, metalness: 0.65 }); }
function addPrimitive(group: THREE.Group, asset: TwinAsset, retrofit: boolean) {
  const kind = semanticKind(asset.className || asset.label); const material = makeMaterial(retrofit); const secondary = makeSecondary(retrofit);
  const sx = Math.max(asset.widthM, 0.04), sy = Math.max(asset.heightM, 0.04), sz = Math.max(asset.depthM, 0.04);
  const box = (w: number, h: number, d: number, x = 0, y = 0, z = 0) => { const mesh = new THREE.Mesh(new THREE.BoxGeometry(w, h, d), material); mesh.position.set(x, y, z); group.add(mesh); return mesh; };
  const cyl = (r: number, h: number, x = 0, y = 0, z = 0, rotX = 0, rotZ = 0) => { const mesh = new THREE.Mesh(new THREE.CylinderGeometry(r, r, h, 28), secondary); mesh.position.set(x, y, z); mesh.rotation.x = rotX; mesh.rotation.z = rotZ; group.add(mesh); return mesh; };
  if (kind === "pump") { box(sx * 0.72, sy * 0.42, sz * 0.82, 0, sy * 0.21, 0); cyl(Math.min(sx, sz) * 0.28, Math.max(sx * 0.48, 0.08), 0, sy * 0.54, 0, 0, Math.PI / 2); cyl(Math.min(sx, sz) * 0.075, Math.max(sx * 0.65, 0.08), -sx * 0.4, sy * 0.38, 0, 0, Math.PI / 2); return; }
  if (kind === "compressor") { box(sx * 0.84, sy * 0.72, sz * 0.82, 0, sy * 0.36, 0); cyl(Math.min(sx, sz) * 0.22, Math.max(sx * 0.8, 0.08), sx * 0.25, sy * 0.43, 0, Math.PI / 2); return; }
  if (kind === "fan") { box(sx * 0.9, sy * 0.7, sz * 0.78, 0, sy * 0.35, 0); const hub = cyl(Math.min(sx, sz) * 0.22, Math.max(Math.min(sx, sz) * 0.08, 0.04), 0, sy * 0.5, sz * 0.42, Math.PI / 2); for (let i = 0; i < 6; i += 1) { const blade = box(sx * 0.25, sy * 0.025, sz * 0.07); blade.position.set(Math.cos(i * Math.PI / 3) * sx * 0.18, sy * 0.5, sz * 0.42 + Math.sin(i * Math.PI / 3) * sz * 0.18); blade.rotation.y = i * Math.PI / 3; } void hub; return; }
  if (kind === "motor") { cyl(Math.min(sx, sz) * 0.39, Math.max(sx * 0.72, 0.08), 0, sy * 0.45, 0, 0, Math.PI / 2); box(sx * 0.22, sy * 0.22, sz * 0.24, -sx * 0.12, sy * 0.83, 0); return; }
  if (kind === "vessel") { cyl(Math.min(sx, sz) * 0.42, Math.max(sy * 0.72, 0.08), 0, sy * 0.38, 0); cyl(Math.min(sx, sz) * 0.46, Math.max(sy * 0.08, 0.04), 0, sy * 0.78, 0); return; }
  if (kind === "panel") { box(sx * 0.9, sy * 0.95, Math.min(sz * 0.35, 0.3), 0, sy * 0.475, 0); for (let i = 0; i < 3; i += 1) box(Math.max(sx * 0.09, 0.025), Math.max(sy * 0.08, 0.025), Math.max(sz * 0.08, 0.025), (-sx * 0.22) + i * sx * 0.22, sy * 0.62, sz * 0.19); return; }
  if (kind === "duct") { box(sx, sy, sz, 0, sy * 0.5, 0); return; }
  if (kind === "window" || kind === "door") { const edges = new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(sx, sy, Math.max(sz, 0.04))), new THREE.LineBasicMaterial({ color: retrofit ? 0xd8a84e : 0x42e2cd, transparent: true, opacity: 0.9 })); edges.position.y = sy * 0.5; group.add(edges); return; }
  box(sx * 0.92, sy * 0.92, sz * 0.92, 0, sy * 0.46, 0);
}

function TwinCanvas({ twin, fallbackClass, width, depth, height, retrofit, mode }: { twin: TwinModel; fallbackClass: string; width: number; depth: number; height: number; retrofit: number; mode: ViewMode }) {
  const host = useRef<HTMLDivElement>(null); const [fps, setFps] = useState(0);
  useEffect(() => {
    const element = host.current; if (!element) return;
    const scene = new THREE.Scene(); scene.background = new THREE.Color(0x040707);
    const camera = new THREE.PerspectiveCamera(42, Math.max(element.clientWidth, 1) / Math.max(element.clientHeight, 1), 0.01, 500);
    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false, powerPreference: "high-performance" }); renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.65)); renderer.setSize(element.clientWidth, element.clientHeight); renderer.outputColorSpace = THREE.SRGBColorSpace; element.replaceChildren(renderer.domElement);
    const root = new THREE.Group(); scene.add(root);
    const floor = new THREE.Mesh(new THREE.BoxGeometry(width, 0.035, depth), new THREE.MeshStandardMaterial({ color: 0x101817, roughness: 0.92 })); floor.position.y = -0.02; root.add(floor);
    const grid = new THREE.GridHelper(Math.max(width, depth) * 1.25, 28, 0x24413d, 0x102522); grid.position.y = 0.01; root.add(grid);
    const isEquipment = twin.scope === "equipment";
    if (!isEquipment) {
      for (const room of twin.rooms) { const roomMesh = new THREE.Mesh(new THREE.BoxGeometry(room.widthM, 0.025, room.depthM), new THREE.MeshBasicMaterial({ color: 0x1c3531, transparent: true, opacity: 0.65, wireframe: true })); roomMesh.position.set(room.x + room.widthM / 2 - width / 2, 0.035, room.y + room.depthM / 2 - depth / 2); root.add(roomMesh); }
      for (const wall of twin.walls) { const dx = wall.b.x - wall.a.x, dy = wall.b.y - wall.a.y; const length = Math.hypot(dx, dy); const wallMesh = new THREE.Mesh(new THREE.BoxGeometry(length, wall.heightM, Math.max(wall.thicknessM, 0.02)), new THREE.MeshStandardMaterial({ color: 0x6aaea5, transparent: true, opacity: 0.38, roughness: 0.8 })); wallMesh.position.set((wall.a.x + wall.b.x) / 2 - width / 2, wall.heightM / 2, (wall.a.y + wall.b.y) / 2 - depth / 2); wallMesh.rotation.y = -Math.atan2(dy, dx); root.add(wallMesh); }
      for (const opening of twin.openings) { const openingMesh = new THREE.Mesh(new THREE.BoxGeometry(opening.widthM, Math.max(height * 0.55, 1.5), 0.03), new THREE.MeshBasicMaterial({ color: opening.type === "window" ? 0x6adbd0 : 0xd8a84e, transparent: true, opacity: 0.32, wireframe: true })); openingMesh.position.set(opening.x - width / 2, Math.max(height * 0.48, 1.2), opening.y - depth / 2); root.add(openingMesh); }
    }
    const assets: TwinAsset[] = twin.assets.length ? twin.assets : [{ id: "fallback", label: fallbackClass, className: fallbackClass, x: 0, y: 0, widthM: Math.max(width * 0.25, 0.5), depthM: Math.max(depth * 0.25, 0.5), heightM: Math.max(height * 0.35, 0.8), rotationDeg: 0, source: "inferred", confidence: 0.2 }];
    const retrofitLevel = Math.max(0, Math.min(100, retrofit));
    for (const asset of assets) {
      const group = new THREE.Group(); addPrimitive(group, asset, mode === "retrofit"); group.position.set(asset.x + asset.widthM / 2 - width / 2, 0, asset.y + asset.depthM / 2 - depth / 2); group.rotation.y = THREE.MathUtils.degToRad(asset.rotationDeg || 0); root.add(group);
      if (mode === "retrofit" && retrofitLevel > 0) { const halo = new THREE.Mesh(new THREE.BoxGeometry(asset.widthM * 1.08, asset.heightM * 1.08, asset.depthM * 1.08), new THREE.MeshBasicMaterial({ color: 0xd8a84e, wireframe: true, transparent: true, opacity: 0.08 + retrofitLevel / 1100 })); halo.position.set(asset.widthM / 2 - width / 2 + asset.x, asset.heightM / 2, asset.depthM / 2 - depth / 2 + asset.y); halo.rotation.y = THREE.MathUtils.degToRad(asset.rotationDeg || 0); root.add(halo); }
    }
    const outline = new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(width, height, depth)), new THREE.LineBasicMaterial({ color: 0x78b8ae, transparent: true, opacity: 0.22 })); outline.position.y = height / 2; root.add(outline);
    if (mode === "retrofit" && retrofitLevel > 0) { const layer = new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(width * 0.985, height * 0.985, depth * 0.985)), new THREE.LineBasicMaterial({ color: 0xd8a84e, transparent: true, opacity: 0.18 + retrofitLevel / 800 })); layer.position.y = height / 2; root.add(layer); }
    scene.add(new THREE.HemisphereLight(0xbbeee8, 0x07100f, 1.55)); const key = new THREE.DirectionalLight(0xffffff, 2.2); key.position.set(5, 8, 6); scene.add(key); const rim = new THREE.PointLight(mode === "retrofit" ? 0xd8a84e : 0x3fe0c9, 3.3, Math.max(width, depth, height) * 4); rim.position.set(-3, 3, -4); scene.add(rim);
    let theta = 0.55, phi = 0.78, radius = Math.max(width, depth, height) * 2.35, dragging = false, px = 0, py = 0, raf = 0, frames = 0, last = performance.now();
    const updateCamera = () => { const target = new THREE.Vector3(0, Math.max(height * 0.34, 0.4), 0); camera.position.set(target.x + Math.sin(theta) * Math.cos(phi) * radius, target.y + Math.sin(phi) * radius, target.z + Math.cos(theta) * Math.cos(phi) * radius); camera.lookAt(target); };
    updateCamera();
    const down = (event: PointerEvent) => { dragging = true; px = event.clientX; py = event.clientY; renderer.domElement.setPointerCapture(event.pointerId); };
    const move = (event: PointerEvent) => { if (!dragging) return; theta -= (event.clientX - px) * 0.008; phi = Math.max(0.12, Math.min(1.4, phi + (event.clientY - py) * 0.006)); px = event.clientX; py = event.clientY; updateCamera(); };
    const up = () => { dragging = false; };
    const wheel = (event: WheelEvent) => { event.preventDefault(); radius = Math.max(Math.max(width, depth, height) * 1.15, Math.min(Math.max(width, depth, height) * 5, radius * (1 + event.deltaY * 0.0009))); updateCamera(); };
    renderer.domElement.addEventListener("pointerdown", down); renderer.domElement.addEventListener("pointermove", move); renderer.domElement.addEventListener("pointerup", up); renderer.domElement.addEventListener("pointercancel", up); renderer.domElement.addEventListener("wheel", wheel, { passive: false });
    const resize = () => { if (!host.current) return; camera.aspect = Math.max(host.current.clientWidth, 1) / Math.max(host.current.clientHeight, 1); camera.updateProjectionMatrix(); renderer.setSize(host.current.clientWidth, host.current.clientHeight); }; window.addEventListener("resize", resize);
    const animate = (now: number) => { frames += 1; if (now - last > 1000) { setFps(Math.round(frames * 1000 / (now - last))); frames = 0; last = now; } renderer.render(scene, camera); raf = requestAnimationFrame(animate); }; raf = requestAnimationFrame(animate);
    return () => { cancelAnimationFrame(raf); window.removeEventListener("resize", resize); renderer.domElement.removeEventListener("pointerdown", down); renderer.domElement.removeEventListener("pointermove", move); renderer.domElement.removeEventListener("pointerup", up); renderer.domElement.removeEventListener("pointercancel", up); renderer.domElement.removeEventListener("wheel", wheel); renderer.dispose(); element.replaceChildren(); };
  }, [depth, fallbackClass, height, mode, retrofit, twin, width]);
  return <div ref={host} className="relative h-[430px] w-full overflow-hidden"><div className="pointer-events-none absolute left-4 top-4 z-10 flex gap-2 font-mono text-[7px] uppercase tracking-[.13em]"><span className="border border-teal/25 bg-black/55 px-2 py-1 text-teal">Live digital shadow</span><span className="border border-steel/20 bg-black/55 px-2 py-1 text-steel">{fps || "—"} FPS</span></div><div className="pointer-events-none absolute bottom-4 left-4 z-10 font-mono text-[7px] uppercase tracking-[.12em] text-steel">drag to orbit · wheel to zoom · {mode === "retrofit" ? `${retrofit}% retrofit counterfactual` : "scan-reconstructed observed state"}</div></div>;
}

export default function AssetTwinViewportV2({ scope, title, assetClass, evidenceIds, values, twin }: Props) {
  const [tab, setTab] = useState<"model" | "evidence">("model"); const [mode, setMode] = useState<ViewMode>("current"); const [retrofit, setRetrofit] = useState(45);
  const width = twin?.overall.widthM ?? n(values, "geometry_width_m", "width_m") ?? 4; const depth = twin?.overall.depthM ?? n(values, "geometry_depth_m", "depth_m") ?? 3; const height = twin?.overall.heightM ?? n(values, "geometry_height_m", "height_m") ?? 2.4;
  const asset: InteropAsset = useMemo(() => ({ id: "asset-core", name: title, scope, className: assetClass, widthM: width, depthM: depth, heightM: height, capacityKW: n(values, "capacity_kw"), powerKW: n(values, "power_kw"), evidenceIds }), [assetClass, depth, evidenceIds, height, scope, title, values, width]);
  const manifest = useMemo(() => buildInteropManifest(asset, values, twin), [asset, twin, values]); const safeName = title.replace(/\W+/g, "-").replace(/^-|-$/g, "") || "overhaul-digital-shadow"; const generated = Boolean(twin);
  const displayedAssets = twin?.assets || []; const topology = twin ? `${twin.rooms.length} spaces · ${twin.walls.length} walls · ${twin.openings.length} openings · ${twin.assets.length} assets` : "reconstruction pending";
  return <section className="overflow-hidden border border-teal/20 bg-[#070b0b] shadow-[0_24px_100px_rgba(0,0,0,.22)]">
    <div className="flex flex-wrap items-start justify-between gap-4 border-b border-steel/10 px-5 py-4"><div><p className="font-mono text-[8px] uppercase tracking-[.16em] text-teal">Reconstructed digital shadow · semantic CAD bridge</p><h2 className="mt-1 font-display text-3xl">Scan → scene → retrofit counterfactual.</h2><p className="mt-1 max-w-3xl text-[10px] leading-5 text-steel">The 3D scene is built from the generated model itself: every supplied asset, room, wall and opening is placed from its reconstructed geometry instead of replacing the scan with one generic object.</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={!generated} onClick={() => downloadText(`${safeName}.obj`, buildTwinObj(twin!), "text/plain;charset=utf-8")} className="border border-teal/30 px-3 py-2 font-mono text-[8px] uppercase text-teal disabled:opacity-30">Export OBJ</button><button type="button" disabled={!generated} onClick={() => downloadText(`${safeName}.dxf`, buildTwinDxf(twin!), "application/dxf")} className="border border-steel/25 px-3 py-2 font-mono text-[8px] uppercase text-paper disabled:opacity-30">Export DXF</button><button type="button" onClick={() => downloadText(`${safeName}.overhaul.json`, JSON.stringify(manifest, null, 2), "application/json")} className="border border-steel/25 px-3 py-2 font-mono text-[8px] uppercase text-paper">Shadow manifest</button></div></div>
    <div className="grid gap-0 xl:grid-cols-[1fr_.75fr]"><div className="relative min-h-[430px] border-b border-steel/10 bg-[#040707] xl:border-b-0 xl:border-r">{twin ? <TwinCanvas twin={twin} fallbackClass={assetClass} width={width} depth={depth} height={height} retrofit={retrofit} mode={mode}/> : <div className="flex h-[430px] items-center justify-center p-8 text-center font-mono text-[9px] uppercase tracking-[.12em] text-steel">No reconstructed geometry yet — supply the scan or explicit dimensions.</div>}</div>
      <aside className="p-5"><div className="grid grid-cols-2 gap-1 border border-steel/15 bg-black/20 p-1"><button type="button" onClick={() => setMode("current")} className={`px-3 py-2 font-mono text-[8px] uppercase ${mode === "current" ? "bg-teal text-navy" : "text-steel"}`}>Observed state</button><button type="button" onClick={() => setMode("retrofit")} className={`px-3 py-2 font-mono text-[8px] uppercase ${mode === "retrofit" ? "bg-clay text-navy" : "text-steel"}`}>Retrofit what-if</button></div>
        {mode === "retrofit" ? <div className="mt-4 border border-clay/20 bg-clay/5 p-3"><div className="flex justify-between font-mono text-[8px] uppercase text-steel"><span>Intervention intensity</span><span className="text-clay">{retrofit}%</span></div><input aria-label="Retrofit intensity" type="range" min="5" max="100" value={retrofit} onChange={(event) => setRetrofit(Number(event.target.value))} className="mt-3 w-full accent-[#d8a84e]"/><p className="mt-2 text-[8px] leading-4 text-steel">Visual counterfactual only. Engineering outputs remain governed by evidence and physics calculations.</p></div> : null}
        <div className="mt-4 flex border border-steel/15 bg-black/20 p-1"><button type="button" onClick={() => setTab("model")} className={`flex-1 px-3 py-2 font-mono text-[8px] uppercase ${tab === "model" ? "bg-teal text-navy" : "text-steel"}`}>Model telemetry</button><button type="button" onClick={() => setTab("evidence")} className={`flex-1 px-3 py-2 font-mono text-[8px] uppercase ${tab === "evidence" ? "bg-teal text-navy" : "text-steel"}`}>Evidence links</button></div>
        {tab === "model" ? <div className="mt-4 space-y-3"><Data label="Semantic scope" value={`${twin?.scope || scope} · ${twin?.className || assetClass}`} /><Data label="Overall" value={`${width.toFixed(2)} × ${depth.toFixed(2)} × ${height.toFixed(2)} m`} /><Data label="Geometry basis" value={twin?.geometryBasis || "pending"} /><Data label="Metric status" value={twin?.geometryStatus || "pending"} /><Data label="Shadow confidence" value={twin ? `${Math.round(twin.confidence * 100)}%` : "pending"}/><Data label="Topology" value={topology}/>{displayedAssets.length ? <div className="border border-steel/10 p-3"><p className="font-mono text-[7px] uppercase text-steel">Reconstructed assets</p><div className="mt-2 space-y-1 text-[9px] text-paper">{displayedAssets.slice(0, 8).map((item) => <div key={item.id} className="flex justify-between gap-3"><span className="truncate">{item.label}</span><span className="shrink-0 font-mono text-teal">{item.widthM.toFixed(2)}×{item.depthM.toFixed(2)}×{item.heightM.toFixed(2)} m</span></div>)}</div></div> : null}{twin?.warnings?.length ? <div className="border border-amber-200/20 bg-amber-200/[.025] p-3 text-[9px] leading-4 text-amber-100">{twin.warnings.slice(0, 4).map((warning, index) => <p key={index}>› {warning}</p>)}</div> : null}</div> : <div className="mt-4 space-y-2">{evidenceIds.map((id) => <div key={id} className="border border-steel/10 p-3"><p className="font-mono text-[7px] uppercase text-teal">linked evidence</p><p className="mt-1 break-all text-[9px] text-paper">{id}</p></div>)}<p className="mt-4 text-[9px] leading-5 text-steel">Metric geometry is traceable to evidence. Photo-only geometry stays relative until an independent metric anchor exists.</p></div>}</aside></div>
    <div className="grid grid-cols-2 border-t border-steel/10 sm:grid-cols-4"><Data label="Representation" value="3D reconstructed scene"/><Data label="State pair" value="Observed ↔ What-if"/><Data label="Interaction" value="Orbit + zoom"/><Data label="Interop" value="OBJ · DXF · JSON"/></div>
  </section>;
}
function Data({ label, value }: { label: string; value: string }) { return <div className="border border-steel/10 p-3"><p className="font-mono text-[7px] uppercase text-steel">{label}</p><p className="mt-1 text-sm text-paper">{value}</p></div>; }
