"use client";

import { useEffect, useMemo, useState } from "react";
import { buildDecisionProvenanceGraph, type ProvenanceDecision } from "@/lib/engineering/provenanceGraph";

type Extraction = { evidenceId?: string; evidenceType?: string; observations?: Array<{ field:string; value:string; numericValue:number|null; unit:string|null; confidence:number; sourceText:string }> };

type Scope = "building" | "facility" | "equipment";

export default function DecisionProvenancePanel({ scope, extracts, label }:{scope:Scope;extracts:Extraction[];label?:string}){
 const [decision,setDecision]=useState<ProvenanceDecision|null>(null);
 useEffect(()=>{try{const raw=sessionStorage.getItem("overhaul:latest-intervention");if(raw)setDecision(JSON.parse(raw));}catch{setDecision(null)}},[]);
 const graph=useMemo(()=>buildDecisionProvenanceGraph({scope,assessmentLabel:label,extracts,decision}),[scope,label,extracts,decision]);
 const counts=useMemo(()=>graph.nodes.reduce<Record<string,number>>((acc,node)=>{acc[node.type]=(acc[node.type]||0)+1;return acc},{}),[graph]);
 const chain=["evidence","observation","asset-model","expectation","residual","diagnosis","intervention","simulation","economics","decision"] as const;
 return <section className="mx-auto mt-4 max-w-[1500px] px-4 pb-8 sm:px-6 lg:px-8"><div className="border border-steel/20 bg-black/15 p-5"><div className="flex flex-col gap-2 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-teal">Decision provenance graph</p><h2 className="font-display mt-1 text-3xl sm:text-4xl">Why does OVERHAUL believe this?</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-steel">Every decision is traceable from evidence through observations, the normalized asset model, independent expectations, residuals, diagnosis, simulation and economics. Missing evidence stays visible instead of becoming an assumption.</p></div><div className="font-mono text-[9px] uppercase text-steel">{graph.nodes.length} nodes · {graph.edges.length} relations</div></div><div className="mt-5 grid gap-2 md:grid-cols-5 lg:grid-cols-10">{chain.map(type=><div key={type} className="border border-steel/15 p-3"><p className="font-mono text-[8px] uppercase text-steel">{type}</p><p className="mt-2 text-lg text-paper">{counts[type]||0}</p></div>)}</div><div className="mt-5 grid gap-2 md:grid-cols-5">{chain.slice(0,5).map((type,i)=><div key={type} className="border border-teal/15 bg-teal/5 p-3"><p className="font-mono text-[8px] text-teal">0{i+1}</p><p className="mt-2 text-xs uppercase">{type}</p><p className="mt-1 text-[10px] text-steel">{graph.nodes.filter(n=>n.type===type).slice(0,2).map(n=>n.label).join(" · ")||"not established"}</p></div>)}</div><div className="mt-2 grid gap-2 md:grid-cols-5">{chain.slice(5).map((type,i)=><div key={type} className="border border-steel/15 p-3"><p className="font-mono text-[8px] text-steel">0{i+6}</p><p className="mt-2 text-xs uppercase">{type}</p><p className="mt-1 text-[10px] text-steel">{graph.nodes.filter(n=>n.type===type).slice(0,2).map(n=>n.label).join(" · ")||"pending"}</p></div>)}</div><div className="mt-5 border border-clay/20 bg-clay/5 p-4"><p className="font-mono text-[9px] uppercase text-clay">Audit rule</p><p className="mt-2 text-xs leading-5 text-steel">A numeric recommendation is only as strong as its evidence path. Observations retain confidence and source text; engineering models retain their equation; the graph keeps those relationships queryable.</p></div></div></section>;
}
