"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import FinalReportView from "./FinalReportView";
import Twin3DCanvas from "./Twin3DCanvas";
import { calculateMachineBaseline, calculateMachineRetrofit, extractBillEnergy } from "@/lib/engineering/machineRetrofitCalculations";
import { sanitizeTwinModel, type TwinModel } from "@/lib/engineering/twinModel";

type Values = Record<string, number | string | null | undefined>;
type Assessment = { assessmentSubject?: "building" | "facility" | "equipment"; assetClass?: string | null; siteName?: string | null; assetAgeYears?: number | null; industry?: string; assessmentGoal?: string } | null;
type Observation = { field: string; value: string; numericValue: number | null; unit: string | null; confidence: number };
type Extraction = { sourceName?: string; sourceKind?: string; observations?: Observation[] };
type Finding = { id: string; type: string; label: string; confidence: number; views: number[]; evidence: string; engineeringStatus: string; requiredVerification?: string[]; retrofitRelevance?: string };
type Fusion = { findings?: Finding[]; coverage?: { viewsAnalysed?: number }; nextEvidence?: string[] } | null;

const readJson = <T,>(key: string, fallback: T): T => { try { return JSON.parse(sessionStorage.getItem(key) || "null") ?? fallback; } catch { return fallback; } };
const canonical = (field: string) => field.toLowerCase().trim().replace(/[()\-\/]+/g, "_").replace(/\s+/g, "_").replace(/_+/g, "_");
const numberValue = (values: Values, ...keys: string[]) => { for (const key of keys) { const value = Number(values[key]); if (Number.isFinite(value) && value > 0) return value; } return null; };
const format = (value: number | null, digits = 1) => value == null || !Number.isFinite(value) ? "—" : value.toLocaleString("en-IN", { maximumFractionDigits: digits });
const rupees = (value: number | null) => value == null || !Number.isFinite(value) ? "—" : `₹${Math.round(value).toLocaleString("en-IN")}`;

export default function UniversalReportView() {
  const [assessment, setAssessment] = useState<Assessment>(null);
  useEffect(() => { setAssessment(readJson<Assessment>("overhaul:assessment", null)); }, []);
  return assessment?.assessmentSubject === "equipment" ? <MachineReport assessment={assessment} /> : <FinalReportView />;
}

function MachineReport({ assessment }: { assessment: NonNullable<Assessment> }) {
  const [extracts, setExtracts] = useState<Extraction[]>([]);
  const [values, setValues] = useState<Values>({});
  const [twin, setTwin] = useState<TwinModel | null>(null);
  const [fusion, setFusion] = useState<Fusion>(null);
  const [scanCaptured, setScanCaptured] = useState(false);

  useEffect(() => {
    const sync = () => {
      const nextExtracts = readJson<Extraction[]>("overhaul:evidence-extractions", []);
      const supplemental = readJson<Values>("overhaul:supplemental-values", {});
      const nextValues: Values = {};
      nextExtracts.forEach((item) => (item.observations || []).forEach((observation) => { if (observation.numericValue != null && Number.isFinite(observation.numericValue)) nextValues[canonical(observation.field)] = observation.numericValue; }));
      Object.entries(supplemental).forEach(([key, value]) => { if (nextValues[key] == null && typeof value === "number" && Number.isFinite(value)) nextValues[canonical(key)] = value; });
      setExtracts(nextExtracts);
      setValues(nextValues);
      setTwin(sanitizeTwinModel(readJson<unknown>("overhaul:twin-model", null)));
      setFusion(readJson<Fusion>("overhaul:scan-fusion", null));
      setScanCaptured(Boolean(readJson<unknown>("overhaul:room-scan", null)));
    };
    sync();
    const events = ["overhaul:evidence-change", "overhaul:supplemental-change", "overhaul:twin-change", "overhaul:scan-fusion-change"];
    events.forEach((name) => window.addEventListener(name, sync));
    return () => events.forEach((name) => window.removeEventListener(name, sync));
  }, []);

  const billObservations = useMemo(() => extracts.filter((item) => /bill|electric|utility|energy/i.test(`${item.sourceKind || ""} ${item.sourceName || ""}`)).flatMap((item) => item.observations || []), [extracts]);
  const bill = useMemo(() => extractBillEnergy(billObservations), [billObservations]);
  const baseline = useMemo(() => calculateMachineBaseline({ loadKW: numberValue(values, "load_kw", "observed_load_kw", "operating_load_kw"), ratedCapacityKW: numberValue(values, "capacity_kw", "rated_capacity_kw"), powerKW: numberValue(values, "power_kw", "observed_power_kw", "input_power_kw"), efficiency: numberValue(values, "efficiency"), cop: numberValue(values, "cop"), runtimeHours: numberValue(values, "annual_hours", "runtime_hours", "annual_runtime_hours"), electricityRateINRPerKWh: numberValue(values, "electricity_rate_inr_per_kwh", "electricity_rate", "tariff_inr_per_kwh"), billEnergyKWh: numberValue(values, "bill_energy_kwh", "annual_bill_energy_kwh") ?? bill.totalKWh, billMonths: numberValue(values, "bill_history_months", "bill_months") }), [values, bill]);
  const retrofit = useMemo(() => calculateMachineRetrofit({ loadKW: numberValue(values, "load_kw", "observed_load_kw", "operating_load_kw"), ratedCapacityKW: numberValue(values, "capacity_kw", "rated_capacity_kw"), powerKW: numberValue(values, "power_kw", "observed_power_kw", "input_power_kw"), efficiency: numberValue(values, "efficiency"), cop: numberValue(values, "cop"), runtimeHours: numberValue(values, "annual_hours", "runtime_hours", "annual_runtime_hours"), electricityRateINRPerKWh: numberValue(values, "electricity_rate_inr_per_kwh", "electricity_rate", "tariff_inr_per_kwh"), targetEfficiency: numberValue(values, "proposed_efficiency", "target_efficiency"), targetCOP: numberValue(values, "proposed_cop", "target_cop"), targetRuntimeHours: numberValue(values, "proposed_runtime_hours", "target_runtime_hours"), title: "Explicit retrofit target" }), [values]);

  const capacity = numberValue(values, "capacity_kw", "rated_capacity_kw");
  const load = numberValue(values, "load_kw", "observed_load_kw", "operating_load_kw");
  const inputPower = numberValue(values, "power_kw", "observed_power_kw", "input_power_kw");
  const utilization = capacity && load ? load / capacity : null;
  const savingPercent = retrofit && baseline.annualEnergyKWh ? (retrofit.energySavingKWh || 0) / baseline.annualEnergyKWh * 100 : null;
  const overall = twin?.overall || { widthM: 2.4, depthM: 1.5, heightM: 1.8 };
  const findings = fusion?.findings || [];

  return <main className="machine-report min-h-screen bg-[#f4f2eb] text-[#171c19]">
    <div className="no-print sticky top-0 z-30 flex items-center justify-between gap-4 border-b border-[#d6d1c5] bg-[#f4f2eb]/95 px-4 py-3 backdrop-blur sm:px-7"><div><p className="font-mono text-[8px] uppercase tracking-[.18em] text-[#7b6a3e]">OVERHAUL · machine retrofit dossier</p><p className="mt-1 text-xs text-[#5c655f]">{assessment.siteName || assessment.assetClass || "Equipment assessment"}</p></div><div className="flex gap-2"><Link href="/assessment" className="border border-[#c9c4b8] px-3 py-2 font-mono text-[8px] uppercase">Back to analysis</Link><button type="button" onClick={() => window.print()} className="border border-[#7b6a3e] bg-[#171c19] px-4 py-2 font-mono text-[8px] uppercase text-[#f4edda]">Print / PDF</button></div></div>
    <article className="mx-auto max-w-[1200px] space-y-6 px-4 py-6 sm:px-7 sm:py-10">
      <section className="bg-[#121713] p-7 text-[#ece8dd] shadow-xl sm:p-10"><p className="font-mono text-[8px] uppercase tracking-[.24em] text-[#c6a65b]">Evidence → twin → physics → retrofit → verify</p><h1 className="mt-4 font-display text-5xl leading-[.94] sm:text-6xl">{assessment.siteName || assessment.assetClass || "Machine / appliance"}</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[#a9b0aa]">Machine-specific analysis using scan evidence, model/nameplate evidence, available electricity history, age, user anchors and deterministic calculations.</p><div className="mt-8 grid gap-3 sm:grid-cols-4"><DarkStat label="Asset" value={assessment.assetClass || "Equipment"}/><DarkStat label="Age" value={assessment.assetAgeYears != null ? `${format(assessment.assetAgeYears,0)} yr` : "Not supplied"}/><DarkStat label="Evidence" value={`${extracts.length} sources`}/><DarkStat label="Scan" value={scanCaptured ? "captured" : "not captured"}/></div></section>
      <Section title="01 · Evidence vs engineering" kicker="what entered the calculation"><div className="grid gap-5 lg:grid-cols-2"><Panel title="Submitted / extracted"><Row label="Rated capacity" value={capacity != null ? `${format(capacity)} kW` : "Not established"}/><Row label="Observed duty" value={load != null ? `${format(load)} kW` : "Not established"}/><Row label="Observed input power" value={inputPower != null ? `${format(inputPower)} kW` : "Not measured"}/><Row label="Runtime" value={numberValue(values,"annual_hours","runtime_hours","annual_runtime_hours") != null ? `${format(numberValue(values,"annual_hours","runtime_hours","annual_runtime_hours"),0)} h/yr` : "Not established"}/><Row label="Bill energy" value={bill.totalKWh != null ? `${format(bill.totalKWh)} kWh extracted` : "Not extracted"}/><Row label="Bill months" value={numberValue(values,"bill_history_months","bill_months") != null ? format(numberValue(values,"bill_history_months","bill_months"),0) : "Not established"}/></Panel><Panel title="Deterministic interpretation"><Row label="Calculated power" value={baseline.calculatedPowerKW != null ? `${format(baseline.calculatedPowerKW)} kW` : "Blocked"}/><Row label="Projected annual energy" value={baseline.annualEnergyKWh != null ? `${format(baseline.annualEnergyKWh)} kWh/yr` : "Blocked"}/><Row label="Annualised bill" value={baseline.annualizedBillEnergyKWh != null ? `${format(baseline.annualizedBillEnergyKWh)} kWh/yr` : "Not annualised"}/><Row label="Utilisation" value={utilization != null ? `${format(utilization*100,0)}%` : "Not established"}/><Row label="Basis" value={baseline.baselineBasis.join(" · ") || "Insufficient evidence"}/></Panel></div></Section>
      <Section title="02 · Digital twin" kicker="browser / cad representation"><div className="overflow-hidden border border-[#273029] bg-[#050808]"><div className="min-h-[560px]"><Twin3DCanvas scope="equipment" mode="observed" model={twin} widthM={overall.widthM} depthM={overall.depthM} heightM={overall.heightM} capacityKW={capacity} loadKW={load} powerKW={inputPower} currentLoadKW={load} proposedLoadKW={load} currentPowerKW={inputPower} proposedPowerKW={retrofit?.powerKW ?? inputPower} currentUtilization={utilization} proposedUtilization={utilization} savingPercent={savingPercent} title={assessment.assetClass || "Equipment twin"}/></div><div className="grid gap-3 border-t border-[#273029] p-5 text-[#e7e3d8] sm:grid-cols-5"><DarkRow label="Width" value={`${format(overall.widthM,2)} m`}/><DarkRow label="Depth" value={`${format(overall.depthM,2)} m`}/><DarkRow label="Height" value={`${format(overall.heightM,2)} m`}/><DarkRow label="Basis" value={twin?.geometryBasis || "parametric"}/><DarkRow label="Confidence" value={twin ? `${format(twin.confidence*100,0)}%` : "—"}/></div></div></Section>
      <Section title="03 · Scan findings" kicker="visual evidence is not a fault claim">{findings.length ? <div className="grid gap-3 lg:grid-cols-2">{findings.map((finding) => <div key={finding.id} className="border border-[#d6d1c5] bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[7px] uppercase text-[#7b6a3e]">{finding.type}</p><h3 className="mt-1 text-sm">{finding.label}</h3></div><span className="font-mono text-[8px] text-[#5f6a64]">{format(finding.confidence*100,0)}% visual</span></div><p className="mt-3 text-xs leading-5 text-[#5e6661]">{finding.evidence || "No evidence text recorded."}</p><p className="mt-3 font-mono text-[8px] uppercase text-[#7b6a3e]">status · {finding.engineeringStatus}</p>{finding.requiredVerification?.length ? <p className="mt-2 text-[10px] leading-4 text-[#6a726d]">Verify · {finding.requiredVerification.join("; ")}</p> : null}{finding.retrofitRelevance ? <p className="mt-2 text-[10px] leading-4 text-[#6a726d]">Retrofit relevance · {finding.retrofitRelevance}</p> : null}</div>)}</div> : <Empty text="No fused scan findings are recorded. Absence of a visual finding is not treated as proof that the asset is healthy."/>}</Section>
      <Section title="04 · Problem calculation" kicker="reference before intervention"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Observed power" value={inputPower != null ? `${format(inputPower)} kW` : "Not measured"}/><Metric label="Calculated power" value={baseline.calculatedPowerKW != null ? `${format(baseline.calculatedPowerKW)} kW` : "Needs duty + efficiency/COP"}/><Metric label="Measured − calculated" value={baseline.currentPowerKW != null && baseline.calculatedPowerKW != null ? `${format(baseline.currentPowerKW-baseline.calculatedPowerKW,2)} kW` : "Cannot establish"}/></div>{baseline.gaps.length ? <div className="mt-4 border border-[#d6d1c5] bg-white p-5"><p className="font-mono text-[8px] uppercase text-[#7b6a3e]">Calculation gates</p>{baseline.gaps.map((gap)=><p key={gap} className="mt-2 text-xs leading-5 text-[#656d68]">{gap}</p>)}</div> : null}</Section>
      <Section title="05 · Retrofit what-if" kicker="explicit counterfactual"><div className="grid gap-5 lg:grid-cols-2"><Panel title="Current state"><Row label="Power" value={baseline.currentPowerKW != null ? `${format(baseline.currentPowerKW)} kW` : baseline.calculatedPowerKW != null ? `${format(baseline.calculatedPowerKW)} kW calculated` : "—"}/><Row label="Annual energy" value={baseline.annualEnergyKWh != null ? `${format(baseline.annualEnergyKWh)} kWh/yr` : "—"}/><Row label="Annual cost" value={baseline.annualCostINR != null ? rupees(baseline.annualCostINR) : "—"}/></Panel><Panel title="Counterfactual"><Row label="Intervention" value={retrofit?.title || "No explicit target supplied"}/><Row label="Target power" value={retrofit?.powerKW != null ? `${format(retrofit.powerKW)} kW` : "—"}/><Row label="Annual energy" value={retrofit?.annualEnergyKWh != null ? `${format(retrofit.annualEnergyKWh)} kWh/yr` : "—"}/><Row label="Energy change" value={retrofit?.energySavingKWh != null ? `${format(retrofit.energySavingKWh)} kWh/yr` : "—"}/><Row label="Cost change" value={retrofit?.costSavingINR != null ? rupees(retrofit.costSavingINR) : "Tariff/baseline required"}/><Row label="Basis" value={retrofit?.basis || "No calculation performed"}/></Panel></div><div className="mt-4 border border-[#7b6a3e] bg-[#faf6e9] p-5 text-sm leading-6">{retrofit ? "Counterfactual computed from explicit target parameter(s)." : "No numeric retrofit outcome is claimed until a defensible target/reference exists."}</div></Section>
      <Section title="06 · Verification handoff" kicker="measure reality after intervention"><div className="grid gap-3 md:grid-cols-3"><Panel title="Baseline"><Row label="Energy" value={baseline.annualEnergyKWh != null ? `${format(baseline.annualEnergyKWh)} kWh/yr` : "Establish baseline"}/></Panel><Panel title="Post-retrofit"><Row label="Measured energy" value="Enter measured result"/></Panel><Panel title="Variance"><Row label="Prediction vs measurement" value="Compare and record variance"/></Panel></div>{fusion?.nextEvidence?.length ? <div className="mt-4 border border-[#d6d1c5] bg-white p-5"><p className="font-mono text-[8px] uppercase text-[#7b6a3e]">Next evidence</p><p className="mt-2 text-xs leading-5 text-[#626a65]">{fusion.nextEvidence.join(" · ")}</p></div> : null}</Section>
      <footer className="border-t border-[#cec9bd] py-7"><div className="flex flex-wrap justify-between gap-4 font-mono text-[8px] uppercase text-[#717a75]"><span>OVERHAUL · machine retrofit record</span><span>Evidence → Twin → Physics → Retrofit → Verify</span></div></footer>
    </article>
    <style jsx global>{`@media print {.no-print{display:none!important}.machine-report{background:white!important}.machine-report article{max-width:none!important;padding:0!important}.machine-report section{break-inside:avoid}}`}</style>
  </main>;
}

function Section({ title, kicker, children }: { title: string; kicker: string; children: React.ReactNode }) { return <section><div className="mb-3"><p className="font-mono text-[7px] uppercase tracking-[.18em] text-[#7b6a3e]">{kicker}</p><h2 className="mt-1 font-display text-3xl text-[#1d2421]">{title}</h2></div>{children}</section>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="border border-[#d6d1c5] bg-white p-5"><p className="font-mono text-[8px] uppercase tracking-[.12em] text-[#727b76]">{title}</p><div className="mt-3">{children}</div></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 border-b border-[#ebe7df] py-2 last:border-0"><span className="text-[9px] text-[#6d756f]">{label}</span><span className="max-w-[68%] text-right font-mono text-[9px] text-[#1c211e]">{value}</span></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="border border-[#d6d1c5] bg-white p-4"><p className="font-mono text-[7px] uppercase text-[#727b76]">{label}</p><p className="mt-2 font-mono text-lg">{value}</p></div>; }
function DarkStat({ label, value }: { label: string; value: string }) { return <div className="border border-[#354038] p-4"><p className="font-mono text-[7px] uppercase text-[#87918b]">{label}</p><p className="mt-2 text-sm">{value}</p></div>; }
function DarkRow({ label, value }: { label: string; value: string }) { return <div><p className="font-mono text-[7px] uppercase text-[#7d8881]">{label}</p><p className="mt-1 font-mono text-[9px] text-[#eee9dd]">{value}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="border border-[#d6d1c5] bg-white p-5 text-sm text-[#656d67]">{text}</div>; }
